WebSite_2/Controllers/AdminGalleryController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSite_2.Models;
using WebSite_2.Models.ImageModels;



namespace WebSite_2.Controllers
{
    public class AdminGalleryController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: AdminGallery
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult UploadImage()
        {
            return View();
        }
        public ActionResult UImage3()
        {
            return View();
        }


        public ActionResult UImage2()
        {
            return View();
        }

        public ActionResult UImage()
        {
            return View();
        }


        [HttpPost]
        public ActionResult UploadImage(HttpPostedFileBase image)
        {

            if (image != null)
            {
                var imagePath = Server.MapPath("~/Images/");

                var imageFolder = "~/Images/";
                Image img = new Image();
                UploadedImage uploaded = new UploadedImage();
                uploaded.Duplicate = true;
                var Name = Path.GetFileNameWithoutExtension(image.FileName);
                var ext = Path.GetExtension(image.FileName);
                var size = (image.ContentLength);
                var type = image.ContentType;
                var fullName = Path.GetFileName(image.FileName);
                var check = DublicateImage(Name, size);
                if (check == false)
                {


                    img.Name = Name;
                    img.PublishDate = DateTime.Now;
                    img.Size = size;
                    img.ImageExt = ext;
                    img.Src = Name + ext;
                    img.UrlName = imagePath + Name + ext;
                    
                    var save = Path.Combine(imagePath, Name + ext);
                    image.SaveAs(save);
                    


                    db.Images.Add(img);
                    db.SaveChanges();
                    uploaded.Name = Name;
                    uploaded.Src = Name + ext;
                    uploaded.Duplicate = false;
                    uploaded.ext = ext;

                }
                
                return Json(uploaded, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return RedirectToAction("UploadImage");
            }
        }


        public bool DublicateImage(string name, int size)
        {
            var result = false;
            var check = db.Images.FirstOrDefault(model => model.Name == name && model.Size == size);
            if (check != null)
            {
                result = true;
            }


            return result;
        }



        public PartialViewResult PartialGallery()
        {
            var list = db.Images.ToList();
            return PartialView(list);
        }

    }
}

WebSite_2/Views/AdminGallery/PartialGallery.cshtml
@model List<WebSite_2.Models.ImageModels.Image>

<style>
    .imageContainer{
        width : 33%;
        height : 400px;
        display : inline-block;
    }
    .imageContainer img{
        /*max-width : 100%!important;*/
        max-height : 400px;
    }
</style>





@foreach(var img in Model)
{
    <div class="imageContainer"><img src="/Images/@img.Src" class="col-md-12" name="@img.Name" data-id="@img.ImageID"/></div>
}

WebSite_2/Views/AdminGallery/UImage.cshtml
@{
    ViewBag.Title = "UImage";
}
<style>
    .prev{
        max-height : 400px;
        max-width : 25%;
    }
</style>
<input type="file" class="file" />
<div class="upload-preview"></div>

<script src="~/Scripts/jquery-3.1.1.js"></script>
<script>
    $(document).ready(function () {
        var preview = $(".upload-preview");

        $(".file").change(function (event) {
            var input = $(event.currentTarget);
            var file = input[0].files[0];
            var reader = new FileReader();
            reader.onload = function (e) {
                image_base64 = e.target.result;
                preview.append("<img class='prev' src='" + image_base64 + "'/>");
            };
            reader.readAsDataURL(file);
        });
    });

</script>

WebSite_2/Views/AdminGallery/UImage2.cshtml
@{
    ViewBag.Title = "UImage2";
}
<form id="form1" runat="server">
    <input type='file' id="imgInp" />
    <img id="blah" src="#" alt="your image" />
</form>



<script src="~/Scripts/jquery-3.1.1.js"></script>
<script>
    function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#imgInp").change(function () {
        readURL(this);
    });
</script>

WebSite_2/Views/AdminGallery/UImage3.cshtml
@{
    ViewBag.Title = "UImage3";
}







<style>
    .prev {
        max-height: 400px;
        max-width: 25%;
    }
</style>
<input type="file" class="file" />
<input type="button" class="submitBtn" value="Submit" />

<div class="upload-preview"></div>

<link href="~/Content/materialize/css/materialize.css" rel="stylesheet" />
<script src="~/Scripts/materialize/materialize.js"></script>
<script src="~/Scripts/jquery-3.1.1.js"></script>
<script>
    $(document).ready(function () {
        var preview = $(".upload-preview");
        var fileInput = $(".file");
        $(".file").change(function (event) {
            var input = $(event.currentTarget);
            var file = input[0].files[0];
            var reader = new FileReader();
            reader.onload = function (e) {
                image_base64 = e.target.result;
                preview.append("<img class='prev' src='" + image_base64 + "'/>");
            };
            reader.readAsDataURL(file);
        });
    });


    $(".submitBtn").on("click", function () {
        if($(".file").has("img"))
        {
            $.ajax({
                url: "/AdminGallery/UploadImage",
                type: 'POST',
                data: formData,
                cache: false,
                contentType: false,
                processData: false,
                success: function (data) {
                    $("#uploadInput").val("");
                    $("#uploadGif").remove();
                    if (data.Duplicate == false) {
                        $("ul.uploadedImage").append("<li><img src='/Images/" + data.Src + "' data-name='" + data.Name + data.ext + "'/>" + data.Name + "</li>");

                    }
                    else {

                        var $toastContent = $('<span>I am toast content</span>');
                        Materialize.toast($toastContent, 5000);


                    }
                }
            });
        }
    });
</script>

WebSite_2/Views/AdminGallery/UploadImage.cshtml
@{
    ViewBag.Title = "UploadImage";
}
<style>
    .uploadPart {
        /*display: block;*/
    }

    .uploadedImage li {
        list-style: none;
        display: inline-block;
        width: 25%;
        height: 400px;
    }

    .uploadedImage img {
        max-height: 400px;
        max-width: 100%;
    }

    #uploadGif {
        max-height: 400px;
        max-width: 100%;
    }

    .preview {
        max-height: 800px;
        /*max-width: 80%;*/
        display: inline-block;
        position: relative;
    }

        .preview img {
            max-height: 600px;
            margin: 0;
            /*max-width : 20%;*/
            /*display : inline-block;*/
        }

        .preview btns {
            position: absolute;
            bottom: 0;
        }
</style>
<link href="~/Content/materialize/css/materialize.css" rel="stylesheet" />
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<div class="row">
    <div class="galleryPart col-md-6">
        @Html.Action("PartialGallery", "AdminGallery")
    </div>

    <div class="col-md-6">
        <div class="uploadPart">
            <form action="UploadImage" method="post" class="UploadImage">
                <input type="file" class="file" id="uploadInput" value="image" name="image" accept=".jpg,.jpeg,.png" />
                <input type="submit" value="submit" />
            </form>
        </div>
    </div>
</div>
<div class="uploadPart col-md-6">


    <div class="previewList uploadPart col-md-12">

    </div>
    
    <div class="col-xs-12">
        <ul class="uploadedImage"></ul>
    </div>


</div>

<script src="~/Scripts/jquery-3.1.1.js"></script>
@*<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>*@
<script src="~/Scripts/materialize/materialize.min.js"></script>

<script>
    //var formData = null;

    //function upload() {

    //    $(".uploadedImage").append("<li id='uploadGif'><img  src='/LoadingGif/loading (2).gif' /></li>");
    //    alert(formData);
    //    $.ajax({
    //        url: "/AdminGallery/UploadImage",
    //        type: 'POST',
    //        data: formData,
    //        cache: false,
    //        contentType: false,
    //        processData: false,
    //        success: function (data) {

    //            $("#uploadGif").remove();
    //            if (data.Duplicate == false) {
    //                $("ul.uploadedImage").append("<li><img src='/Images/" + data.Src + "' data-name='" + data.Name + "'/>" + data.Name + "</li>");
    //            }
    //            else {
    //                alert("It's already saved Database!!!!");
    //            }
    //        }
    //    });
    //////////}


    function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $(".previewList").empty();
                $(".previewList").append('<div class="col-xs-12 preview"><img src="' + e.target.result + '" class="" /><div class="col-xs-12 btns"><button class="col-md-6"><i class="material-icons">clear</i></button><button class="col-md-6 submitBtn"><i class="material-icons">done</i></button></div></div>')
                //$('.preview').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $(".file").change(function () {
        readURL(this);
    });



    //$(document).on("click",".submitBtn", function () {
    //    alert("deneme");
    //});
    $(document).ready(function () {




        $(".UploadImage").on("submit", function (event) {


            //$(document).on("click",".submitBtn",function(event){

            //});
            //alert("start");
            event.preventDefault();
            var inputVal = $("#uploadInput").val();
            //console.log(inputVal);
            if (inputVal != "") {
                //alert("if");
                var formData = new FormData(this);
                //alert(formData);
                if ($(".uploadedImage").has("li")) {

                    $(".uploadedImage li img").each(function () {

                        var text = $(this).attr("data-name");
                        var up = $("#uploadInput").val();

                        if (text == up) {
                            //alert("Same Image is in the List");

                            var $toastContent = $('<span>Same Image is in the List</span>');
                            Materialize.toast($toastContent, 3000);

                            throw new Error("The Same Image In The List");
                        }

                    });
                }






                //$(".uploadedImage").append("<li id='uploadGif'><img  src='/LoadingGif/loading (2).gif' /></li>");
                //alert(formData);
                $.ajax({
                    url: "/AdminGallery/UploadImage",
                    type: 'POST',
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        $("#uploadInput").val("");
                        $("#uploadGif").remove();
                        if (data.Duplicate == false) {
                            $("ul.uploadedImage").append("<li><img src='/Images/" + data.Src + "' data-name='" + data.Name + data.ext + "'/>" + data.Name + "</li>");

                        }
                        else {
                            var $toastContent = $('<span>There is the same image in the database</span>');
                            Materialize.toast($toastContent, 5000);

                        }
                    }
                });

            }
        });
    });
</script>